# ---
# deployment:
#   tasks:
#     - /bin/npm install
#     - /bin/npm run build
#     - export DEPLOY_PATH=/home/hxhryqpz/public_html/
#     - /bin/rm -rf $DEPLOY_PATH*
#     - /bin/cp -R build/* $DEPLOY_PATH